In [1]:
import numpy as np
import pandas as pd

In [11]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D']*5,
    'Region': ['East', 'West', 'North', 'South']*5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice']*5
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    732     24   John
1  2023-01-02       B   West    300     93   Mary
2  2023-01-03       C  North    163     41    Bob
3  2023-01-04       D  South    916     75  Alice
4  2023-01-05       A   East    744     51   John
5  2023-01-06       B   West    123     91   Mary
6  2023-01-07       C  North    724     29    Bob
7  2023-01-08       D  South    631     77  Alice
8  2023-01-09       A   East    390     65   John
9  2023-01-10       B   West    771     29   Mary
10 2023-01-11       C  North    923     34    Bob
11 2023-01-12       D  South    191     21  Alice
12 2023-01-13       A   East    112     69   John
13 2023-01-14       B   West    970     75   Mary
14 2023-01-15       C  North    861     41    Bob
15 2023-01-16       D  South    574     95  Alice
16 2023-01-17       A   East    803     26   John
17 2023-01-18       B   West    611     12   Mary
18 2023-01-19       C  North    658     12    Bob
19 2023-01-20       D  South    240     30  Alice

In [17]:
pd.pivot_table(data=df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     556.2    NaN    NaN    NaN
North      NaN    NaN  665.8    NaN
South      NaN    NaN    NaN  510.4
West       NaN  555.0    NaN    NaN

In [18]:
pd.pivot_table(data=df,values=['Sales','Units'],index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     556.2    NaN    NaN    NaN  47.0   NaN   NaN   NaN
North      NaN    NaN  665.8    NaN   NaN   NaN  31.4   NaN
South      NaN    NaN    NaN  510.4   NaN   NaN   NaN  59.6
West       NaN  555.0    NaN    NaN   NaN  60.0   NaN   NaN

### cross tabs

In [20]:
pd.crosstab(index=df['Region'],columns=df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0