In [265]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [266]:
df=pd.read_csv("cardekho_imputated.csv",index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB

In [268]:
df.isna().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [269]:
df.columns

Index(['car_name', 'brand', 'model', 'vehicle_age', 'km_driven', 'seller_type',
       'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power',
       'seats', 'selling_price'],
      dtype='object')

In [270]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [271]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [272]:
df.drop(columns=['car_name', 'brand'],axis=1,inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [273]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [274]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [275]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [276]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [277]:
x=df.drop(columns=['selling_price'],axis=1)
y=df['selling_price']

In [278]:
oneH_feature = ['transmission_type', 'fuel_type', 'seller_type']
label_feature = ['model']   # MUST be a list
stand_feature = x.select_dtypes(exclude="object").columns.tolist()

In [279]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=42)

In [280]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

oneH_feature = ['transmission_type', 'fuel_type', 'seller_type']
label_feature = ['model']
stand_feature = x.select_dtypes(exclude='object').columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("onehot", OneHotEncoder(drop='first', handle_unknown='ignore'), oneH_feature),
        ("ordinal", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), label_feature),
        ("scaler", StandardScaler(), stand_feature)
    ]
)

In [281]:
type(xtrain)

pandas.core.frame.DataFrame

In [282]:
xtr = preprocessor.fit_transform(xtrain)
xts = preprocessor.transform(xtest)

In [283]:
xtr

array([[ 1.        ,  0.        ,  0.        , ..., -0.76298882,
        -0.89557228, -0.40252148],
       [ 0.        ,  1.        ,  0.        , ...,  0.93281626,
         0.95728977, -0.40252148],
       [ 1.        ,  0.        ,  0.        , ..., -0.54572581,
        -0.61611653, -0.40252148],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.93218479,
        -0.77956292, -0.40252148],
       [ 1.        ,  0.        ,  0.        , ..., -0.54957117,
        -0.43153484, -0.40252148],
       [ 0.        ,  0.        ,  0.        , ..., -0.04006058,
         0.07078099, -0.40252148]])

In [284]:
onehot_cols = (
    preprocessor
    .named_transformers_['onehot']
    .get_feature_names_out(oneH_feature)
)
ordinal_cols = label_feature
scaled_cols = stand_feature
final_columns = list(onehot_cols) + ordinal_cols + scaled_cols
import pandas as pd

xtrain= pd.DataFrame(xtr, columns=final_columns, index=xtrain.index)
xtest= pd.DataFrame(xts, columns=final_columns, index=xtest.index)

In [285]:
xtrain

,transmission_type_Manual,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,model,vehicle_age,km_driven,mileage,engine,max_power,seats
14389,1.0,0.0,0.0,0.0,1.0,0.0,0.0,82.0,0.988218,-0.000504,-0.439588,-0.762989,-0.895572,-0.402521
6203,0.0,1.0,0.0,0.0,0.0,0.0,0.0,69.0,-0.010659,1.050645,-0.108487,0.932816,0.957290,-0.402521
18625,1.0,0.0,0.0,0.0,1.0,0.0,0.0,71.0,-0.343618,-0.152704,-0.852265,-0.545726,-0.616117,-0.402521
15681,1.0,0.0,0.0,0.0,1.0,1.0,0.0,116.0,-0.676576,-0.369307,-0.276437,-0.549571,-0.432239,-0.402521
9063,1.0,0.0,0.0,0.0,1.0,0.0,0.0,53.0,-1.009535,-1.157621,-0.204458,-0.549571,-0.431535,-0.402521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6581,1.0,1.0,0.0,0.0,0.0,0.0,0.0,41.0,0.322300,1.742114,0.244208,-0.451514,-0.268558,2.066875
17029,1.0,0.0,0.0,0.0,1.0,0.0,0.0,93.0,1.654135,0.087966,-0.878657,0.221424,0.069607,-0.402521
6839,1.0,0.0,0.0,0.0,1.0,1.0,0.0,98.0,0.322300,-0.850646,0.181826,-0.932185,-0.779563,-0.402521
1104,1.0,0.0,0.0,0.0,1.0,0.0,0.0,116.0,-1.342494,-0.970981,-0.276437,-0.549571,-0.431535,-0.402521
9295,0.0,0.0,0.0,0.0,1.0,1.0,0.0,23.0,-1.342494,-0.609977,0.126643,-0.040061,0.070781,-0.402521

In [286]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [287]:
xtrain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11558 entries, 14389 to 9295
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transmission_type_Manual      11558 non-null  float64
 1   fuel_type_Diesel              11558 non-null  float64
 2   fuel_type_Electric            11558 non-null  float64
 3   fuel_type_LPG                 11558 non-null  float64
 4   fuel_type_Petrol              11558 non-null  float64
 5   seller_type_Individual        11558 non-null  float64
 6   seller_type_Trustmark Dealer  11558 non-null  float64
 7   model                         11558 non-null  float64
 8   vehicle_age                   11558 non-null  float64
 9   km_driven                     11558 non-null  float64
 10  mileage                       11558 non-null  float64
 11  engine                        11558 non-null  float64
 12  max_power                     11558 non-null  float64
 13  seats                         11558 non-null  float64
dtypes: float64(14)
memory usage: 1.3 MB

In [290]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(xtrain,ytrain)

RandomForestRegressor()

In [291]:
y_pred=rfr.predict(xtest)

In [296]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error
print(mean_squared_error(y_pred,ytest))
print(mean_absolute_error(y_pred,ytest))
print(mean_absolute_percentage_error(y_pred,ytest))

58074495095.94716
104589.8095378826
0.1325124264819401