In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=pd.DataFrame({
    'city':['New york','london','tokyo','delhi','london','paris','tokyo'],
    'price':[120,220,45,320,432,120,450]
})
df

       city  price
0  New york    120
1    london    220
2     tokyo     45
3     delhi    320
4    london    432
5     paris    120
6     tokyo    450

In [8]:
dictr=df.groupby('city')['price'].mean().to_dict()
df['encoded_price']=df['city'].map(dictr)
df

       city  price  encoded_price
0  New york    120          120.0
1    london    220          326.0
2     tokyo     45          247.5
3     delhi    320          320.0
4    london    432          326.0
5     paris    120          120.0
6     tokyo    450          247.5

In [12]:
tips=sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:
tips_dic=tips.groupby('time')['total_bill'].mean().to_dict()
tips_dic

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_11532\3695915413.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_dic=tips.groupby('time')['total_bill'].mean().to_dict()

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [18]:
import seaborn as sns
import pandas as pd

# Load dataset
tips = sns.load_dataset('tips')

# Compute mean total_bill for each time category
encoding_map = tips.groupby('time')['total_bill'].mean().sort_values().to_dict()

# Apply target guided ordinal encoding
tips['time_encoded'] = tips['time'].map(encoding_map)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_11532\1750569849.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  encoding_map = tips.groupby('time')['total_bill'].mean().sort_values().to_dict()